Controllers/ContaBancariaController.cs
using Microsoft.AspNetCore.Mvc;
using Minhalabcompras.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Minhalabcompras.Controllers
{
    public class ContaBancariaController : Controller
    {
        public IActionResult Index()
        {
            List<ContaBancaria> MinhasContas = Repositorio.Contas;
            return View(MinhasContas);

        }
        public IActionResult Conta()
        {
            return View();
        }

        [HttpGet]
        public IActionResult NovaContaBancaria()
        {
            return View();
        }

        [HttpPost]
        public IActionResult NovaContaBancaria(ContaBancaria MinhaNovaContaBancaria)
        {
            if (ModelState.IsValid)
            {
                 Repositorio.AddContaBancaria(MinhaNovaContaBancaria);
                return View("NovaConta", MinhaNovaContaBancaria);
            }
            else
            {
                return View();
            }

        }

        public IActionResult RemoverContaBancaria(ContaBancaria MinhaNovaContaBancaria)
        {
            Repositorio.Contas.Clear();
            return View("SemContasBancarias", MinhaNovaContaBancaria);
        }
   
    }
}

Controllers/DespesasController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Minhalabcompras.Controllers
{
    public class DespesasController : Controller
    {

        public IActionResult Despesa()
        {
            return View();
        }

        public IActionResult NovaDespesa()
        {
            return View();
        }
    }
}

Controllers/ProdutosController.cs
using Microsoft.AspNetCore.Mvc;
using Minhalabcompras.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Minhalabcompras.Controllers
{
    public class ProdutosController : Controller
    {
        public IActionResult Index()
        {
           List<Produto> MeusProdutos=Repositorio.Produtos;
            return View(MeusProdutos);
        }

        [HttpGet]
        public IActionResult NovoProduto()
        {
            return View();
        }

        [HttpPost]

        public IActionResult NovoProduto(Produto MeuNovoProduto)
        {
            if (ModelState.IsValid)
            {
                Repositorio.AddProduto(MeuNovoProduto);
                return View("ProdutoConfirmado", MeuNovoProduto);
            }
            else
            {
                return View();
            }
        }

        public IActionResult EliminarProdutos(Produto MeuNovoProduto)
        {
            Repositorio.EliminarProdutos(MeuNovoProduto);
            return View("ProdutosEliminados", MeuNovoProduto);
        }
    }
}

Views/Shared/Conceito.cshtml
@{
    ViewData["Title"] = "Compras - Conceito";
}
<p>
    <h3>Aprender a programar é o objetivo e Conceito da construção deste site.</h3>
</p>

<br />
<br />
<a href="/Home/Index">Página Principal</a>

Views/Shared/MeuLayout.cshtml
@{
    ViewData["Title"] = "Compras - My Layout";
}

<h2>Entrada</h2>
<br />
<h5 class="card-title" >DA2</h5>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Minhalabcompras</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Minhalabcompras</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="MeuLayout">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Despesas" asp-action="Despesa">Despesa</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Conceito">Conceito</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ContaBancaria" asp-action="Index">Contas Bancárias</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Produtos" asp-action="Index">Produtos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Tempo">Tempo</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Minhalabcompras - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>